version: '3.9'

services:
  node_app:
    build: .
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
    command: "node server.js"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
