version: '3.9'

services:
  node_app:
    container_name: nodejs_app
    build: .
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
      - redis
    command: "node --env-file environments/docker.env server.js"

  mongodb:
    container_name: MongoDB
    image: mongo
    ports:
      - "27017:27017"

  redis:
    container_name: Redis
    image: redis
    ports:
      - "6379:6379"
